java_library(
    name = "model",
    srcs = glob(["src/main/java/**/*.java"]),
    plugins = ["//:immutables-generate"],
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:org_immutables_value_annotations",
    ],
)
